name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install main dependencies
        run: make install
      - name: Lint scripts
        run: make lint
      - name: Lint styles
        run: make slint
